/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_ConeJoint */

#ifndef _Included_com_jme3_bullet_joints_ConeJoint
#define _Included_com_jme3_bullet_joints_ConeJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    createJoint
 * Signature: (JJLcom/jme3/math/Vector3f;Lcom/jme3/math/Matrix3f;Lcom/jme3/math/Vector3f;Lcom/jme3/math/Matrix3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_ConeJoint_createJoint
  (JNIEnv *, jobject, jlong, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    createJoint1
 * Signature: (JLcom/jme3/math/Vector3f;Lcom/jme3/math/Matrix3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_ConeJoint_createJoint1
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    getFrameOffsetA
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_ConeJoint_getFrameOffsetA
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    getFrameOffsetB
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_ConeJoint_getFrameOffsetB
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    setAngularOnly
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_ConeJoint_setAngularOnly
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_ConeJoint
 * Method:    setLimit
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_ConeJoint_setLimit
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
