/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_NativeLibrary */

#ifndef _Included_com_jme3_bullet_util_NativeLibrary
#define _Included_com_jme3_bullet_util_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_util_NativeLibrary
 * Method:    isDebug
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_util_NativeLibrary_isDebug
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_bullet_util_NativeLibrary
 * Method:    isDoublePrecision
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_util_NativeLibrary_isDoublePrecision
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_bullet_util_NativeLibrary
 * Method:    setStartupMessageEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeLibrary_setStartupMessageEnabled
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
