/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_NativeSoftBodyUtil */

#ifndef _Included_com_jme3_bullet_util_NativeSoftBodyUtil
#define _Included_com_jme3_bullet_util_NativeSoftBodyUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_util_NativeSoftBodyUtil_numAxes
#define com_jme3_bullet_util_NativeSoftBodyUtil_numAxes 3L
/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    updateAnchorMesh
 * Signature: (JLjava/nio/FloatBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_updateAnchorMesh
  (JNIEnv *, jclass, jlong, jobject, jboolean);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    updateClusterMesh
 * Signature: (JLjava/nio/FloatBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_updateClusterMesh
  (JNIEnv *, jclass, jlong, jobject, jboolean);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    updateMesh
 * Signature: (JLjava/nio/IntBuffer;Ljava/nio/FloatBuffer;Ljava/nio/FloatBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_updateMesh__JLjava_nio_IntBuffer_2Ljava_nio_FloatBuffer_2Ljava_nio_FloatBuffer_2ZZ
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jboolean, jboolean);

/*
 * Class:     com_jme3_bullet_util_NativeSoftBodyUtil
 * Method:    updateMesh
 * Signature: (JLjava/nio/FloatBuffer;Ljava/nio/FloatBuffer;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_util_NativeSoftBodyUtil_updateMesh__JLjava_nio_FloatBuffer_2Ljava_nio_FloatBuffer_2ZZ
  (JNIEnv *, jclass, jlong, jobject, jobject, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
