/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_debug_DebugTools */

#ifndef _Included_com_jme3_bullet_debug_DebugTools
#define _Included_com_jme3_bullet_debug_DebugTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_debug_DebugTools
 * Method:    setStartupMessageEnabled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_debug_DebugTools_setStartupMessageEnabled
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
