/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_EmptyShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_EmptyShape
#define _Included_com_jme3_bullet_collision_shapes_EmptyShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_EmptyShape
 * Method:    createShapeNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_EmptyShape_createShapeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
