/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_infos_CompoundMesh */

#ifndef _Included_com_jme3_bullet_collision_shapes_infos_CompoundMesh
#define _Included_com_jme3_bullet_collision_shapes_infos_CompoundMesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_infos_CompoundMesh
 * Method:    addIndexedMesh
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_infos_CompoundMesh_addIndexedMesh
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_jme3_bullet_collision_shapes_infos_CompoundMesh
 * Method:    createEmptyTiva
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_infos_CompoundMesh_createEmptyTiva
  (JNIEnv *, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_infos_CompoundMesh
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_infos_CompoundMesh_finalizeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_collision_shapes_infos_CompoundMesh
 * Method:    getScaling
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_infos_CompoundMesh_getScaling
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_infos_CompoundMesh
 * Method:    setScaling
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_infos_CompoundMesh_setScaling
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
