/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_Convex2dShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_Convex2dShape
#define _Included_com_jme3_bullet_collision_shapes_Convex2dShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_Convex2dShape
 * Method:    createShape
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_Convex2dShape_createShape
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
