/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_util_DebugShapeFactory */

#ifndef _Included_com_jme3_bullet_util_DebugShapeFactory
#define _Included_com_jme3_bullet_util_DebugShapeFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_util_DebugShapeFactory_highResolution
#define com_jme3_bullet_util_DebugShapeFactory_highResolution 1L
#undef com_jme3_bullet_util_DebugShapeFactory_lowResolution
#define com_jme3_bullet_util_DebugShapeFactory_lowResolution 0L
#undef com_jme3_bullet_util_DebugShapeFactory_numAxes
#define com_jme3_bullet_util_DebugShapeFactory_numAxes 3L
/*
 * Class:     com_jme3_bullet_util_DebugShapeFactory
 * Method:    getTriangles
 * Signature: (JILcom/jme3/bullet/util/DebugMeshCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_util_DebugShapeFactory_getTriangles
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_jme3_bullet_util_DebugShapeFactory
 * Method:    getVertices
 * Signature: (JILcom/jme3/bullet/util/DebugMeshCallback;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_util_DebugShapeFactory_getVertices
  (JNIEnv *, jclass, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
