/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_Constraint */

#ifndef _Included_com_jme3_bullet_joints_Constraint
#define _Included_com_jme3_bullet_joints_Constraint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    getConstraintType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_joints_Constraint_getConstraintType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    enableFeedback
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Constraint_enableFeedback
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Constraint_finalizeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    getAppliedImpulse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_Constraint_getAppliedImpulse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    getBreakingImpulseThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_Constraint_getBreakingImpulseThreshold
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    getOverrideIterations
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_joints_Constraint_getOverrideIterations
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    isEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_Constraint_isEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    needsFeedback
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_Constraint_needsFeedback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    overrideIterations
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Constraint_overrideIterations
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    setBreakingImpulseThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Constraint_setBreakingImpulseThreshold
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_Constraint
 * Method:    setEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Constraint_setEnabled
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
