/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_CollisionConfiguration */

#ifndef _Included_com_jme3_bullet_CollisionConfiguration
#define _Included_com_jme3_bullet_CollisionConfiguration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_CollisionConfiguration
 * Method:    createNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_CollisionConfiguration_createNative
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_bullet_CollisionConfiguration
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_CollisionConfiguration_finalizeNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
