/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_ConicalFrustum */

#ifndef _Included_com_jme3_bullet_collision_shapes_ConicalFrustum
#define _Included_com_jme3_bullet_collision_shapes_ConicalFrustum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_ConicalFrustum
 * Method:    createShapeNative
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_ConicalFrustum_createShapeNative
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     com_jme3_bullet_collision_shapes_ConicalFrustum
 * Method:    maxRadius
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_collision_shapes_ConicalFrustum_maxRadius
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_collision_shapes_ConicalFrustum
 * Method:    scaledVolume
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_collision_shapes_ConicalFrustum_scaledVolume
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
