/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_Anchor */

#ifndef _Included_com_jme3_bullet_joints_Anchor
#define _Included_com_jme3_bullet_joints_Anchor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_Anchor
 * Method:    createAnchor
 * Signature: (JIJLcom/jme3/math/Vector3f;ZF)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_Anchor_createAnchor
  (JNIEnv *, jclass, jlong, jint, jlong, jobject, jboolean, jfloat);

/*
 * Class:     com_jme3_bullet_joints_Anchor
 * Method:    setInfluence
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Anchor_setInfluence
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_Anchor
 * Method:    setPivotInB
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_Anchor_setPivotInB
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
