/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_motors_RotationMotor */

#ifndef _Included_com_jme3_bullet_joints_motors_RotationMotor
#define _Included_com_jme3_bullet_joints_motors_RotationMotor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getBounce
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getBounce
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getDamping
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getEquilibrium
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getEquilibrium
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getLowerLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getLowerLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getMaxMotorForce
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getMaxMotorForce
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getParameter
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getParameter
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getServoTarget
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getServoTarget
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getStiffness
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getStiffness
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getTargetVelocity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getTargetVelocity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    getUpperLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_getUpperLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    isDampingLimited
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_isDampingLimited
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    isMotorEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_isMotorEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    isServoEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_isServoEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    isSpringEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_isSpringEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    isStiffnessLimited
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_isStiffnessLimited
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setBounce
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setBounce
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setDamping
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setDampingLimited
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setDampingLimited
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setEquilibrium
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setEquilibrium
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setLowerLimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setLowerLimit
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setMaxMotorForce
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setMaxMotorForce
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setMotorEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setMotorEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setParameter
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setParameter
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setServoEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setServoEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setServoTarget
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setServoTarget
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setSpringEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setSpringEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setStiffness
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setStiffness
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setStiffnessLimited
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setStiffnessLimited
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setTargetVelocity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setTargetVelocity
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationMotor
 * Method:    setUpperLimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationMotor_setUpperLimit
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
