/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_infos_IndexedMesh */

#ifndef _Included_com_jme3_bullet_collision_shapes_infos_IndexedMesh
#define _Included_com_jme3_bullet_collision_shapes_infos_IndexedMesh
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_collision_shapes_infos_IndexedMesh_floatSize
#define com_jme3_bullet_collision_shapes_infos_IndexedMesh_floatSize 4L
#undef com_jme3_bullet_collision_shapes_infos_IndexedMesh_intSize
#define com_jme3_bullet_collision_shapes_infos_IndexedMesh_intSize 4L
#undef com_jme3_bullet_collision_shapes_infos_IndexedMesh_numAxes
#define com_jme3_bullet_collision_shapes_infos_IndexedMesh_numAxes 3L
#undef com_jme3_bullet_collision_shapes_infos_IndexedMesh_vpt
#define com_jme3_bullet_collision_shapes_infos_IndexedMesh_vpt 3L
/*
 * Class:     com_jme3_bullet_collision_shapes_infos_IndexedMesh
 * Method:    createInt
 * Signature: (Ljava/nio/IntBuffer;Ljava/nio/FloatBuffer;IIII)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_infos_IndexedMesh_createInt
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     com_jme3_bullet_collision_shapes_infos_IndexedMesh
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_infos_IndexedMesh_finalizeNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
