/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_GearJoint */

#ifndef _Included_com_jme3_bullet_joints_GearJoint
#define _Included_com_jme3_bullet_joints_GearJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    createJoint
 * Signature: (JJLcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;F)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_GearJoint_createJoint
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jfloat);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    getAxisA
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_GearJoint_getAxisA
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    getAxisB
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_GearJoint_getAxisB
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    getRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_GearJoint_getRatio
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    setAxisA
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_GearJoint_setAxisA
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    setAxisB
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_GearJoint_setAxisB
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_GearJoint
 * Method:    setRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_GearJoint_setRatio
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
