/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_MultiBody */

#ifndef _Included_com_jme3_bullet_MultiBody
#define _Included_com_jme3_bullet_MultiBody
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    addBaseForce
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_addBaseForce
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    addBaseTorque
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_addBaseTorque
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    addLinkForce
 * Signature: (JILcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_addLinkForce
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    addLinkTorque
 * Signature: (JILcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_addLinkTorque
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    canSleep
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_MultiBody_canSleep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    clearConstraintForces
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_clearConstraintForces
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    clearForcesAndTorques
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_clearForcesAndTorques
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    clearVelocities
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_clearVelocities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    create
 * Signature: (IFLcom/jme3/math/Vector3f;ZZ)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_MultiBody_create
  (JNIEnv *, jobject, jint, jfloat, jobject, jboolean, jboolean);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_finalizeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getAngularMomentum
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getAngularMomentum
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBaseInertia
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getBaseInertia
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBaseMass
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_MultiBody_getBaseMass
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBaseOmega
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getBaseOmega
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBasePos
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getBasePos
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBaseVel
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getBaseVel
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getBaseWorldTransform
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getBaseWorldTransform
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getJointPos
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_MultiBody_getJointPos
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getJointVel
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_MultiBody_getJointVel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getKineticEnergy
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_MultiBody_getKineticEnergy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getLinkInertia
 * Signature: (JILcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getLinkInertia
  (JNIEnv *, jobject, jlong, jint, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getLinkMass
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_MultiBody_getLinkMass
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getNumDofs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_MultiBody_getNumDofs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getNumLinks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_MultiBody_getNumLinks
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getParent
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_MultiBody_getParent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    getWorldToBaseRot
 * Signature: (JLcom/jme3/math/Quaternion;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_getWorldToBaseRot
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    hasFixedBase
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_MultiBody_hasFixedBase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    isUsingGlobalVelocities
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_MultiBody_isUsingGlobalVelocities
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    isUsingRK4Integration
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_MultiBody_isUsingRK4Integration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setBaseOmega
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setBaseOmega
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setBasePos
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setBasePos
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setBaseVel
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setBaseVel
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setBaseWorldTransform
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setBaseWorldTransform
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setJointPos
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setJointPos
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setJointVel
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setJointVel
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    setWorldToBaseRot
 * Signature: (JLcom/jme3/math/Quaternion;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_setWorldToBaseRot
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    useGlobalVelocities
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_useGlobalVelocities
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_MultiBody
 * Method:    useRK4Integration
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBody_useRK4Integration
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
