/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_MultiBodySpace */

#ifndef _Included_com_jme3_bullet_MultiBodySpace
#define _Included_com_jme3_bullet_MultiBodySpace
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_MultiBodySpace_AXIS_X
#define com_jme3_bullet_MultiBodySpace_AXIS_X 0L
#undef com_jme3_bullet_MultiBodySpace_AXIS_Y
#define com_jme3_bullet_MultiBodySpace_AXIS_Y 1L
#undef com_jme3_bullet_MultiBodySpace_AXIS_Z
#define com_jme3_bullet_MultiBodySpace_AXIS_Z 2L
/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    addMultiBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_addMultiBody
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    addMultiBodyConstraint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_addMultiBodyConstraint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    createMultiBodySpace
 * Signature: (Lcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_MultiBodySpace_createMultiBodySpace
  (JNIEnv *, jobject, jobject, jobject, jint, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    getNumMultibodies
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_MultiBodySpace_getNumMultibodies
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    getNumMultiBodyConstraints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_MultiBodySpace_getNumMultiBodyConstraints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    removeMultiBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_removeMultiBody
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    removeMultiBodyConstraint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_removeMultiBodyConstraint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    setSolverType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_setSolverType
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
