/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_RotationOrder */

#ifndef _Included_com_jme3_bullet_RotationOrder
#define _Included_com_jme3_bullet_RotationOrder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_RotationOrder
 * Method:    matrixToEuler
 * Signature: (ILcom/jme3/math/Matrix3f;Lcom/jme3/math/Vector3f;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_RotationOrder_matrixToEuler
  (JNIEnv *, jclass, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
