/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_objects_ReducedDeformableBody */

#ifndef _Included_com_jme3_bullet_objects_ReducedDeformableBody
#define _Included_com_jme3_bullet_objects_ReducedDeformableBody
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_NONE
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_NONE 0L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_01
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_01 1L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_02
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_02 2L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_03
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_03 4L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_04
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_04 8L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_05
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_05 16L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_06
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_06 32L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_07
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_07 64L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_08
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_08 128L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_09
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_09 256L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_10
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_10 512L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_11
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_11 1024L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_12
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_12 2048L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_13
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_13 4096L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_14
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_14 8192L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_15
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_15 16384L
#undef com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_16
#define com_jme3_bullet_objects_ReducedDeformableBody_COLLISION_GROUP_16 32768L
#undef com_jme3_bullet_objects_ReducedDeformableBody_massForStatic
#define com_jme3_bullet_objects_ReducedDeformableBody_massForStatic 0.0f
#undef com_jme3_bullet_objects_ReducedDeformableBody_numAxes
#define com_jme3_bullet_objects_ReducedDeformableBody_numAxes 3L
#undef com_jme3_bullet_objects_ReducedDeformableBody_vpe
#define com_jme3_bullet_objects_ReducedDeformableBody_vpe 2L
#undef com_jme3_bullet_objects_ReducedDeformableBody_vpt
#define com_jme3_bullet_objects_ReducedDeformableBody_vpt 3L
/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    create
 * Signature: (J[Lcom/jme3/math/Vector3f;[FI)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_create
  (JNIEnv *, jclass, jlong, jobjectArray, jfloatArray, jint);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    getLinearVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_getLinearVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    isReducedModesEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_isReducedModesEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    pinNode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_pinNode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    setDamping
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_setDamping
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    setLinearVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_setLinearVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    setReducedModes
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_setReducedModes
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    setReducedModesEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_setReducedModesEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_objects_ReducedDeformableBody
 * Method:    setStiffnessScale
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_ReducedDeformableBody_setStiffnessScale
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
