/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_objects_infos_CharacterController */

#ifndef _Included_com_jme3_bullet_objects_infos_CharacterController
#define _Included_com_jme3_bullet_objects_infos_CharacterController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_finalizeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getAngularDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getAngularDamping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getAngularVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getAngularVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getFallSpeed
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getFallSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getGravity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getGravity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getJumpSpeed
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getJumpSpeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getLinearDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getLinearDamping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getLinearVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getLinearVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getMaxPenetrationDepth
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getMaxPenetrationDepth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getMaxSlope
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getMaxSlope
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getStepHeight
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getStepHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getUpDirection
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getUpDirection
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    getWalkOffset
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_getWalkOffset
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    isUsingGhostSweepTest
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_isUsingGhostSweepTest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    jump
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_jump
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    onGround
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_onGround
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    reset
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_reset
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setAngularDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setAngularDamping
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setAngularVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setAngularVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setFallSpeed
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setFallSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setGravity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setGravity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setJumpSpeed
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setJumpSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setLinearDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setLinearDamping
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setLinearVelocity
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setLinearVelocity
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setMaxPenetrationDepth
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setMaxPenetrationDepth
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setMaxSlope
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setMaxSlope
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setStepHeight
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setStepHeight
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setUp
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setUp
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setUseGhostSweepTest
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setUseGhostSweepTest
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    setWalkDirection
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_setWalkDirection
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    warp
 * Signature: (JLcom/jme3/math/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_warp
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_CharacterController
 * Method:    warpDp
 * Signature: (JLcom/simsilica/mathd/Vec3d;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_CharacterController_warpDp
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
