/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_MinkowskiSum */

#ifndef _Included_com_jme3_bullet_collision_shapes_MinkowskiSum
#define _Included_com_jme3_bullet_collision_shapes_MinkowskiSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_MinkowskiSum
 * Method:    createShape
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_MinkowskiSum_createShape
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
