/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_MultiBodySpace */

#ifndef _Included_com_jme3_bullet_MultiBodySpace
#define _Included_com_jme3_bullet_MultiBodySpace
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_MultiBodySpace_AXIS_X
#define com_jme3_bullet_MultiBodySpace_AXIS_X 0L
#undef com_jme3_bullet_MultiBodySpace_AXIS_Y
#define com_jme3_bullet_MultiBodySpace_AXIS_Y 1L
#undef com_jme3_bullet_MultiBodySpace_AXIS_Z
#define com_jme3_bullet_MultiBodySpace_AXIS_Z 2L
/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    addMultiBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_addMultiBody
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    createMultiBodySpace
 * Signature: (Lcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;I)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_MultiBodySpace_createMultiBodySpace
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_jme3_bullet_MultiBodySpace
 * Method:    removeMultiBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_MultiBodySpace_removeMultiBody
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
