/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_HingeJoint */

#ifndef _Included_com_jme3_bullet_joints_HingeJoint
#define _Included_com_jme3_bullet_joints_HingeJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    createJoint
 * Signature: (JJLcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_HingeJoint_createJoint
  (JNIEnv *, jobject, jlong, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    createJoint1
 * Signature: (JLcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_joints_HingeJoint_createJoint1
  (JNIEnv *, jobject, jlong, jobject, jobject, jboolean);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    enableMotor
 * Signature: (JZFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_HingeJoint_enableMotor
  (JNIEnv *, jobject, jlong, jboolean, jfloat, jfloat);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getEnableAngularMotor
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_HingeJoint_getEnableAngularMotor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getFrameOffsetA
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_HingeJoint_getFrameOffsetA
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getFrameOffsetB
 * Signature: (JLcom/jme3/math/Transform;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_HingeJoint_getFrameOffsetB
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getHingeAngle
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_HingeJoint_getHingeAngle
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getLowerLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_HingeJoint_getLowerLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getMaxMotorImpulse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_HingeJoint_getMaxMotorImpulse
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getMotorTargetVelocity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_HingeJoint_getMotorTargetVelocity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    getUpperLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_HingeJoint_getUpperLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    setAngularOnly
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_HingeJoint_setAngularOnly
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_HingeJoint
 * Method:    setLimit
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_HingeJoint_setLimit
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
