/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_HullCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_HullCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_HullCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_collision_shapes_HullCollisionShape_numAxes
#define com_jme3_bullet_collision_shapes_HullCollisionShape_numAxes 3L
/*
 * Class:     com_jme3_bullet_collision_shapes_HullCollisionShape
 * Method:    countHullVertices
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_collision_shapes_HullCollisionShape_countHullVertices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_collision_shapes_HullCollisionShape
 * Method:    createShapeF
 * Signature: (Ljava/nio/FloatBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_HullCollisionShape_createShapeF
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_jme3_bullet_collision_shapes_HullCollisionShape
 * Method:    getHullVerticesF
 * Signature: (JLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_HullCollisionShape_getHullVerticesF
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_HullCollisionShape
 * Method:    recalcAabb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_HullCollisionShape_recalcAabb
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
