/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_PhysicsSoftSpace */

#ifndef _Included_com_jme3_bullet_PhysicsSoftSpace
#define _Included_com_jme3_bullet_PhysicsSoftSpace
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_PhysicsSoftSpace_AXIS_X
#define com_jme3_bullet_PhysicsSoftSpace_AXIS_X 0L
#undef com_jme3_bullet_PhysicsSoftSpace_AXIS_Y
#define com_jme3_bullet_PhysicsSoftSpace_AXIS_Y 1L
#undef com_jme3_bullet_PhysicsSoftSpace_AXIS_Z
#define com_jme3_bullet_PhysicsSoftSpace_AXIS_Z 2L
/*
 * Class:     com_jme3_bullet_PhysicsSoftSpace
 * Method:    addSoftBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_PhysicsSoftSpace_addSoftBody
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_jme3_bullet_PhysicsSoftSpace
 * Method:    createPhysicsSoftSpace
 * Signature: (Lcom/jme3/math/Vector3f;Lcom/jme3/math/Vector3f;IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_PhysicsSoftSpace_createPhysicsSoftSpace
  (JNIEnv *, jobject, jobject, jobject, jint, jboolean);

/*
 * Class:     com_jme3_bullet_PhysicsSoftSpace
 * Method:    getNumSoftBodies
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_PhysicsSoftSpace_getNumSoftBodies
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_PhysicsSoftSpace
 * Method:    getWorldInfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_PhysicsSoftSpace_getWorldInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_PhysicsSoftSpace
 * Method:    removeSoftBody
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_PhysicsSoftSpace_removeSoftBody
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
