/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_PersistentManifolds */

#ifndef _Included_com_jme3_bullet_collision_PersistentManifolds
#define _Included_com_jme3_bullet_collision_PersistentManifolds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_PersistentManifolds
 * Method:    countPoints
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_collision_PersistentManifolds_countPoints
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_collision_PersistentManifolds
 * Method:    getBodyAId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_PersistentManifolds_getBodyAId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_collision_PersistentManifolds
 * Method:    getBodyBId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_PersistentManifolds_getBodyBId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_collision_PersistentManifolds
 * Method:    getPointId
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_PersistentManifolds_getPointId
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
