/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_Box2dShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_Box2dShape
#define _Included_com_jme3_bullet_collision_shapes_Box2dShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_Box2dShape
 * Method:    createShape
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_Box2dShape_createShape
  (JNIEnv *, jclass, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
