/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_StepFlag */

#ifndef _Included_com_jme3_bullet_StepFlag
#define _Included_com_jme3_bullet_StepFlag
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_StepFlag_contactEnded
#define com_jme3_bullet_StepFlag_contactEnded 1L
#undef com_jme3_bullet_StepFlag_contactProcessed
#define com_jme3_bullet_StepFlag_contactProcessed 2L
#undef com_jme3_bullet_StepFlag_contactStarted
#define com_jme3_bullet_StepFlag_contactStarted 4L
/*
 * Class:     com_jme3_bullet_StepFlag
 * Method:    generateJniHeaderFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_StepFlag_generateJniHeaderFile
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
