/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_CustomConvexShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_CustomConvexShape
#define _Included_com_jme3_bullet_collision_shapes_CustomConvexShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_CustomConvexShape
 * Method:    createShapeNative
 * Signature: (Lcom/jme3/math/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_CustomConvexShape_createShapeNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_CustomConvexShape
 * Method:    setScaledInertia
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_CustomConvexShape_setScaledInertia
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
