/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_MultiSphere */

#ifndef _Included_com_jme3_bullet_collision_shapes_MultiSphere
#define _Included_com_jme3_bullet_collision_shapes_MultiSphere
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_collision_shapes_MultiSphere
 * Method:    createShape
 * Signature: ([Lcom/jme3/math/Vector3f;[FI)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_MultiSphere_createShape
  (JNIEnv *, jobject, jobjectArray, jfloatArray, jint);

/*
 * Class:     com_jme3_bullet_collision_shapes_MultiSphere
 * Method:    recalcAabb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_MultiSphere_recalcAabb
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
