/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_joints_motors_RotationalLimitMotor */

#ifndef _Included_com_jme3_bullet_joints_motors_RotationalLimitMotor
#define _Included_com_jme3_bullet_joints_motors_RotationalLimitMotor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getAccumulatedImpulse
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getAccumulatedImpulse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getBounce
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getBounce
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getCurrentPosition
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getCurrentPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getDamping
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getDamping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getERP
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getERP
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getHiLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getHiLimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getLimitSoftness
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getLimitSoftness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getLoLimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getLoLimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getMaxLimitForce
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getMaxLimitForce
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getMaxMotorForce
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getMaxMotorForce
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getNormalCFM
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getNormalCFM
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getStopCFM
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getStopCFM
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    getTargetVelocity
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_getTargetVelocity
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    isEnableMotor
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_isEnableMotor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setAccumulatedImpulse
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setAccumulatedImpulse
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setBounce
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setBounce
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setDamping
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setDamping
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setEnableMotor
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setEnableMotor
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setERP
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setERP
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setHiLimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setHiLimit
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setLimitSoftness
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setLimitSoftness
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setLoLimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setLoLimit
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setMaxLimitForce
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setMaxLimitForce
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setMaxMotorForce
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setMaxMotorForce
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setNormalCFM
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setNormalCFM
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setStopCFM
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setStopCFM
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_joints_motors_RotationalLimitMotor
 * Method:    setTargetVelocity
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_joints_motors_RotationalLimitMotor_setTargetVelocity
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
