/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_objects_infos_SoftBodyMaterial */

#ifndef _Included_com_jme3_bullet_objects_infos_SoftBodyMaterial
#define _Included_com_jme3_bullet_objects_infos_SoftBodyMaterial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    getAngularStiffnessFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_getAngularStiffnessFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    getLinearStiffnessFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_getLinearStiffnessFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    getMaterialId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_getMaterialId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    getVolumeStiffnessFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_getVolumeStiffnessFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    setAngularStiffnessFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_setAngularStiffnessFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    setLinearStiffnessFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_setLinearStiffnessFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_objects_infos_SoftBodyMaterial
 * Method:    setVolumeStiffnessFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_SoftBodyMaterial_setVolumeStiffnessFactor
  (JNIEnv *, jclass, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
