/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_SolverInfo */

#ifndef _Included_com_jme3_bullet_SolverInfo
#define _Included_com_jme3_bullet_SolverInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    copyAllParameters
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_copyAllParameters
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getGlobalCfm
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_SolverInfo_getGlobalCfm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getMinBatch
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_SolverInfo_getMinBatch
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_SolverInfo_getMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getNumIterations
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jme3_bullet_SolverInfo_getNumIterations
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getSplitImpulseErp
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_SolverInfo_getSplitImpulseErp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    getSplitImpulseThreshold
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jme3_bullet_SolverInfo_getSplitImpulseThreshold
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    isSplitImpulseEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_SolverInfo_isSplitImpulseEnabled
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setGlobalCfm
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setGlobalCfm
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setMinBatch
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setMinBatch
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setNumIterations
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setNumIterations
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setSplitImpulseEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setSplitImpulseEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setSplitImpulseErp
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setSplitImpulseErp
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     com_jme3_bullet_SolverInfo
 * Method:    setSplitImpulseThreshold
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_SolverInfo_setSplitImpulseThreshold
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
