/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vhacd4_Vhacd4Hull */

#ifndef _Included_vhacd4_Vhacd4Hull
#define _Included_vhacd4_Vhacd4Hull
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vhacd4_Vhacd4Hull
 * Method:    getNumFloats
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vhacd4_Vhacd4Hull_getNumFloats
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vhacd4_Vhacd4Hull
 * Method:    getPositions
 * Signature: (JLjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_vhacd4_Vhacd4Hull_getPositions
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
