/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vhacd_VHACDParameters */

#ifndef _Included_vhacd_VHACDParameters
#define _Included_vhacd_VHACDParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vhacd_VHACDParameters
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_vhacd_VHACDParameters_create
  (JNIEnv *, jclass);

/*
 * Class:     vhacd_VHACDParameters
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_vhacd_VHACDParameters_finalizeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vhacd_VHACDParameters
 * Method:    getMaxNumVerticesPerCH
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vhacd_VHACDParameters_getMaxNumVerticesPerCH
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vhacd_VHACDParameters
 * Method:    getResolution
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_vhacd_VHACDParameters_getResolution
  (JNIEnv *, jclass, jlong);

/*
 * Class:     vhacd_VHACDParameters
 * Method:    setMaxNumVerticesPerCH
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_vhacd_VHACDParameters_setMaxNumVerticesPerCH
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     vhacd_VHACDParameters
 * Method:    setResolution
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_vhacd_VHACDParameters_setResolution
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
