/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vhacd4_Vhacd4 */

#ifndef _Included_vhacd4_Vhacd4
#define _Included_vhacd4_Vhacd4
#ifdef __cplusplus
extern "C" {
#endif
#undef vhacd4_Vhacd4_vpt
#define vhacd4_Vhacd4_vpt 3L
/*
 * Class:     vhacd4_Vhacd4
 * Method:    compute
 * Signature: (Ljava/nio/FloatBuffer;Ljava/nio/IntBuffer;JZ)V
 */
JNIEXPORT void JNICALL Java_vhacd4_Vhacd4_compute
  (JNIEnv *, jclass, jobject, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
