---
# GitHub Actions workflow for commits pushed to the Libbulletjme repo - master branch only

name: GitHub Pages website
on:
  push:
    branches: [master]

jobs:
  Website:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
      - uses: actions/checkout@v4
      - run: npx antora src/site/ci-playbook.yml
      - run: ./gradlew copyJavadocToSite --console=plain --stacktrace
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/site
