---
# GitHub Actions workflow for commits pushed to the Libbulletjme repo - all branches

name: CI at GitHub
on: [push, workflow_dispatch]

jobs:
  Java21-Linux_ARM64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v6
      - run: |
          ./gradlew -Ptarget=Linux_ARM64 -Ptool=gcc run install --console=plain