---
# GitHub Actions workflow for commits pushed to the Libbulletjme repo - all branches

name: CI at GitHub
on: [push, workflow_dispatch]

jobs:
  Java21-Linux_ARM64:
    if: contains(toJson(github.event.commits), '[ci skip] ') == false
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v6
      - run: |
          ./gradlew -Ptarget=Linux_ARM64 install \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}'
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./gradlew -Partifact=Libbulletjme-Linux_ARM64 -Ptarget=Linux_ARM64 clean release \
            --console=plain \
            -PsigningKeyEncoded='${{ secrets.SIGNING_KEY_ENCODED }}' \
            -PsigningPassword='${{ secrets.SIGNING_PASSWORD }}' \
            -PcentralPassword='${{ secrets.CENTRAL_PASSWORD }}' \
            -PcentralUsername='${{ secrets.CENTRAL_USERNAME }}'
      - name: uploadToCentral.sh
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          bash/uploadToCentral.sh -p '${{ secrets.CENTRAL_PASSWORD }}' \
            -u '${{ secrets.CENTRAL_USERNAME }}'
